"""Batch rendering and deterministic export documentation."""

from __future__ import annotations

import re
from pathlib import Path
from typing import Any

from .io_utils import atomic_write_text
from .rendering import RenderResult, render_script
from .validation import expected_triplet, validate_triplet


def render_all(
    src_dir: Path, export_dir: Path, config: dict[str, Any], timeout: int = 120
) -> list[RenderResult]:
    scripts = sorted(src_dir.resolve().glob("fig_*.py"))
    return [render_script(script, export_dir, config, timeout=timeout) for script in scripts]


def inspect_exports(export_dir: Path, config: dict[str, Any]) -> list[RenderResult]:
    stems = sorted(
        {
            path.stem
            for path in export_dir.glob("*")
            if path.is_file() and path.suffix.lower() in {".pdf", ".svg", ".png"}
        }
    )
    return [
        RenderResult(
            script=Path(),
            stem=stem,
            returncode=0,
            stdout="",
            stderr="",
            outputs=expected_triplet(export_dir, stem),
            issues=validate_triplet(export_dir, stem, config),
        )
        for stem in stems
    ]


def _latex_label(stem: str) -> str:
    return re.sub(r"[^a-z0-9-]+", "-", stem.lower().replace("_", "-")).strip("-") or "figure"


def write_export_docs(
    export_dir: Path, results: list[RenderResult], config: dict[str, Any]
) -> None:
    successful = [result for result in results if result.success]
    width = "0.95\\columnwidth" if config.get("journal") in {"ieee", "acm"} else "\\textwidth"
    latex = ["% Generated by paper-figures. Captions require author review.", ""]
    for result in successful:
        label = _latex_label(result.stem)
        latex.extend(
            [
                f"% Figure: {result.stem}",
                "\\begin{figure}[htbp]",
                "  \\centering",
                f"  \\includegraphics[width={width}]{{{result.stem}.pdf}}",
                f"  \\caption{{TODO: Add caption for {result.stem}}}",
                f"  \\label{{fig:{label}}}",
                "\\end{figure}",
                "",
            ]
        )
    atomic_write_text(export_dir / "latex_snippets.tex", "\n".join(latex))

    readme = [
        "# Exported Paper Figures",
        "",
        f"Journal style: **{config.get('journal', 'generic')}**",
        "",
        "| Figure | PDF | SVG | PNG | Render |",
        "| :--- | :---: | :---: | :---: | :---: |",
    ]
    for result in results:
        mark = "✓" if result.success else "✗"
        format_mark = "✓" if result.success else "—"
        readme.append(
            f"| `{result.stem}` | {format_mark} | {format_mark} | {format_mark} | {mark} |"
        )
    readme.extend(["", "See `latex_snippets.tex` for ready-to-review LaTeX blocks.", ""])
    atomic_write_text(export_dir / "README.md", "\n".join(readme))
