#!/usr/bin/env python3
"""Consolidate all generated figures into the export directory.

Usage:
    python batch_export.py [--src-dir figures/src] [--export-dir figures/export]

Finds all figure scripts in src/, runs them, and collects outputs.
Generates LaTeX snippets and a README with figure inventory.
"""

import argparse
import glob
import json
import os
import subprocess
import sys
from datetime import datetime


def run_all_scripts(src_dir: str, export_dir: str, render_script: str) -> list:
    """Run all figure scripts in src/ directory."""
    scripts = sorted(glob.glob(os.path.join(src_dir, "fig_*.py")))
    if not scripts:
        print(f"No figure scripts found in {src_dir}/")
        return []

    results = []
    for script in scripts:
        name = os.path.basename(script)
        print(f"\n{'='*60}")
        print(f"Rendering: {name}")
        print('='*60)

        result = subprocess.run(
            [sys.executable, render_script, script, "--output-dir", export_dir],
            capture_output=True, text=True
        )

        results.append({
            "script": name,
            "success": result.returncode == 0,
            "output": result.stdout,
            "errors": result.stderr,
        })

        if result.returncode != 0:
            print(f"  FAILED: {result.stderr[:200]}")
        else:
            print(f"  OK")

    return results


def generate_latex_snippets(export_dir: str, style_config: dict) -> None:
    """Generate LaTeX figure snippets for all exported figures."""
    figures = []
    for ext in ["pdf"]:
        for f in sorted(glob.glob(os.path.join(export_dir, f"*.{ext}"))):
            figures.append(f)

    if not figures:
        return

    snippets_path = os.path.join(export_dir, "latex_snippets.tex")
    with open(snippets_path, "w") as f:
        f.write("% LaTeX figure snippets — generated by paper-figures skill\n")
        f.write(f"% Date: {datetime.now().strftime('%Y-%m-%d %H:%M')}\n\n")

        for fig_path in figures:
            name = os.path.splitext(os.path.basename(fig_path))[0]
            # Create label from filename
            label = name.lower().replace(" ", "-").replace("_", "-")

            journal = style_config.get("journal", "generic")
            if journal in ("ieee", "acm"):
                width = "0.95\\columnwidth"
            else:
                width = "\\textwidth"

            f.write(f"% Figure: {name}\n")
            f.write(f"\\begin{{figure}}[htbp]\n")
            f.write(f"  \\centering\n")
            f.write(f"  \\includegraphics[width={width}]{{{name}.pdf}}\n")
            f.write(f"  \\caption{{TODO: Add caption for {name}}}\n")
            f.write(f"  \\label{{fig:{label}}}\n")
            f.write(f"\\end{{figure}}\n\n")

    print(f"  LaTeX snippets: {snippets_path}")


def generate_readme(export_dir: str, results: list, style_config: dict) -> None:
    """Generate README.md with figure inventory."""
    readme_path = os.path.join(os.path.dirname(export_dir), "README.md")

    # Scan export directory for files
    files_by_ext = {"pdf": [], "svg": [], "png": []}
    for ext in files_by_ext:
        for f in sorted(glob.glob(os.path.join(export_dir, f"*.{ext}"))):
            files_by_ext[ext].append(os.path.basename(f))

    with open(readme_path, "w") as f:
        f.write("# Paper Figures\n\n")
        f.write(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}\n\n")
        f.write(f"Journal style: **{style_config.get('journal', 'generic')}**\n\n")

        f.write("## Figures\n\n")
        f.write("| # | Filename | PDF | SVG | PNG |\n")
        f.write("|---|----------|-----|-----|-----|\n")

        all_names = sorted(set(
            os.path.splitext(n)[0]
            for ext_list in files_by_ext.values()
            for n in ext_list
        ))

        for i, name in enumerate(all_names, 1):
            checks = []
            for ext in ["pdf", "svg", "png"]:
                fname = f"{name}.{ext}"
                checks.append("✓" if fname in files_by_ext[ext] else "✗")
            f.write(f"| {i} | {name} | {checks[0]} | {checks[1]} | {checks[2]} |\n")

        f.write(f"\n## Render Results\n\n")
        for r in results:
            status = "✓" if r["success"] else "✗"
            f.write(f"- [{status}] {r['script']}\n")

        f.write(f"\n## LaTeX Usage\n\n")
        f.write(f"See `latex_snippets.tex` for ready-to-paste figure blocks.\n")

    print(f"  README: {readme_path}")


def main():
    parser = argparse.ArgumentParser(description="Batch export all figures")
    parser.add_argument("--src-dir", default="figures/src",
                        help="Source directory with figure scripts")
    parser.add_argument("--export-dir", default="figures/export",
                        help="Export directory for outputs")
    parser.add_argument("--no-run", action="store_true",
                        help="Skip running scripts, just regenerate docs")
    args = parser.parse_args()

    # Resolve paths
    src_dir = os.path.abspath(args.src_dir)
    export_dir = os.path.abspath(args.export_dir)
    os.makedirs(export_dir, exist_ok=True)

    # Load style config
    style_path = os.path.join(os.path.dirname(src_dir), "style_config.json")
    style_config = {}
    if os.path.exists(style_path):
        with open(style_path) as f:
            style_config = json.load(f)

    # Find render script
    skill_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    render_script = os.path.join(skill_dir, "scripts", "render_figure.py")

    if args.no_run:
        results = []
    else:
        print(f"Source:  {src_dir}")
        print(f"Export:  {export_dir}")
        results = run_all_scripts(src_dir, export_dir, render_script)

    # Generate documentation
    print(f"\n{'='*60}")
    print("Generating documentation...")
    print('='*60)
    generate_latex_snippets(export_dir, style_config)
    generate_readme(export_dir, results, style_config)

    # Summary
    success = sum(1 for r in results if r["success"])
    total = len(results)
    print(f"\nDone: {success}/{total} figures exported to {export_dir}/")


if __name__ == "__main__":
    main()
