#!/usr/bin/env python3
"""Execute a matplotlib figure script and verify output.

Usage:
    python render_figure.py <script.py> [--output-dir figures/export]

The script must save figures to the specified output directory.
This wrapper runs it in a subprocess, captures errors, and verifies outputs.
"""

import argparse
import os
import subprocess
import sys
import json
import glob


def find_outputs(script_path: str, output_dir: str) -> dict:
    """Find output files that were likely generated by the script."""
    base = os.path.splitext(os.path.basename(script_path))[0]
    # Remove 'fig_XX_' prefix if present
    if base.startswith("fig_"):
        parts = base.split("_", 2)
        base = parts[-1] if len(parts) > 2 else base

    results = {"pdf": None, "svg": None, "png": None}

    # Search for matching files
    for ext in ["pdf", "svg", "png"]:
        pattern = os.path.join(output_dir, f"*.{ext}")
        candidates = sorted(glob.glob(pattern), key=os.path.getmtime, reverse=True)
        if candidates:
            # Check if any file was modified in the last 30 seconds
            import time
            recent = [c for c in candidates if time.time() - os.path.getmtime(c) < 30]
            if recent:
                results[ext] = recent[0]

    return results


def validate_output(filepath: str, ext: str) -> list:
    """Validate an output file."""
    issues = []

    if not os.path.exists(filepath):
        issues.append(f"File not found: {filepath}")
        return issues

    size = os.path.getsize(filepath)
    if size == 0:
        issues.append(f"Empty file: {filepath}")
        return issues

    if ext == "pdf":
        with open(filepath, "rb") as f:
            header = f.read(5)
        if header != b"%PDF-":
            issues.append(f"Invalid PDF header: {filepath}")

    elif ext == "svg":
        with open(filepath, "r") as f:
            content = f.read(100)
        if "<svg" not in content:
            issues.append(f"Invalid SVG content: {filepath}")

    elif ext == "png":
        with open(filepath, "rb") as f:
            header = f.read(8)
        if header[:4] != b"\x89PNG":
            issues.append(f"Invalid PNG header: {filepath}")

    return issues


def run_script(script_path: str, output_dir: str, timeout: int = 120) -> dict:
    """Run a figure generation script in a subprocess."""
    env = os.environ.copy()
    env["PAPER_FIGURES_OUTPUT_DIR"] = output_dir

    try:
        result = subprocess.run(
            [sys.executable, script_path],
            capture_output=True,
            text=True,
            timeout=timeout,
            env=env,
            cwd=os.path.dirname(os.path.abspath(script_path)),
        )
        return {
            "success": result.returncode == 0,
            "stdout": result.stdout,
            "stderr": result.stderr,
            "returncode": result.returncode,
        }
    except subprocess.TimeoutExpired:
        return {
            "success": False,
            "stdout": "",
            "stderr": f"Script timed out after {timeout}s",
            "returncode": -1,
        }
    except Exception as e:
        return {
            "success": False,
            "stdout": "",
            "stderr": str(e),
            "returncode": -1,
        }


def main():
    parser = argparse.ArgumentParser(description="Render a figure script")
    parser.add_argument("script", help="Path to the figure generation script")
    parser.add_argument("--output-dir", default=None,
                        help="Output directory for figures (default: auto-detect)")
    parser.add_argument("--timeout", type=int, default=120,
                        help="Script execution timeout in seconds")
    args = parser.parse_args()

    script_path = os.path.abspath(args.script)
    if not os.path.exists(script_path):
        print(f"Error: Script not found: {script_path}", file=sys.stderr)
        sys.exit(1)

    # Determine output directory
    if args.output_dir:
        output_dir = os.path.abspath(args.output_dir)
    else:
        # Default: ../export relative to the script's directory
        script_dir = os.path.dirname(script_path)
        output_dir = os.path.join(os.path.dirname(script_dir), "export")

    os.makedirs(output_dir, exist_ok=True)

    print(f"Running: {script_path}")
    print(f"Output:  {output_dir}")
    print("-" * 60)

    # Run the script
    result = run_script(script_path, output_dir, args.timeout)

    if result["stdout"]:
        print("STDOUT:")
        print(result["stdout"])

    if result["stderr"]:
        print("STDERR:")
        print(result["stderr"])

    if not result["success"]:
        print(f"\nFAILED (exit code {result['returncode']})")
        sys.exit(1)

    # Find and validate outputs
    outputs = find_outputs(script_path, output_dir)
    all_valid = True

    print("\nOutput files:")
    for ext, path in outputs.items():
        if path:
            issues = validate_output(path, ext)
            if issues:
                print(f"  {ext.upper()}: ISSUES — {', '.join(issues)}")
                all_valid = False
            else:
                size_kb = os.path.getsize(path) / 1024
                print(f"  {ext.upper()}: OK ({size_kb:.1f} KB) — {path}")
        else:
            print(f"  {ext.upper()}: NOT FOUND")
            all_valid = False

    if all_valid:
        print("\nSUCCESS — All three formats generated")
    else:
        print("\nWARNING — Some outputs missing or invalid")

    sys.exit(0 if all_valid else 1)


if __name__ == "__main__":
    main()
