#!/usr/bin/env python3
"""Initialize figure directory structure in the current project.

Usage:
    python setup_project.py [--output-dir figures]

Creates:
    figures/
        src/          # Python source code for each figure
        export/       # Final PDF + SVG + PNG outputs
        style_config.json
        figure_plan.json
        README.md
"""

import argparse
import json
import os
import sys


def setup_figure_dirs(output_dir: str = "figures") -> None:
    """Create the figure directory structure."""
    dirs = [
        output_dir,
        os.path.join(output_dir, "src"),
        os.path.join(output_dir, "export"),
    ]
    for d in dirs:
        os.makedirs(d, exist_ok=True)
        print(f"  Created: {d}/")


def create_default_style(output_dir: str, journal: str = "generic") -> str:
    """Create default style_config.json."""
    presets = {
        "ieee": {
            "font_family": "serif",
            "font_serif": ["Times New Roman"],
            "font_size": {"label": 10, "tick": 9, "legend": 9, "title": 11},
            "fig_width": {"single": 3.5, "double": 7.16},
            "fig_height_ratio": 0.75,
            "line_width": 1.5,
            "marker_size": 6,
            "dpi": 300,
            "grid": False,
            "spine_top": False,
            "spine_right": False,
        },
        "nature": {
            "font_family": "sans-serif",
            "font_sans": ["Arial", "Helvetica"],
            "font_size": {"label": 9, "tick": 8, "legend": 8, "title": 10},
            "fig_width": {"single": 3.5, "double": 7.0},
            "fig_height_ratio": 0.8,
            "line_width": 1.2,
            "marker_size": 5,
            "dpi": 300,
            "grid": False,
            "spine_top": False,
            "spine_right": False,
        },
        "elsevier": {
            "font_family": "serif",
            "font_serif": ["Times New Roman", "Georgia"],
            "font_size": {"label": 10, "tick": 9, "legend": 9, "title": 11},
            "fig_width": {"single": 3.54, "double": 7.28},
            "fig_height_ratio": 0.75,
            "line_width": 1.5,
            "marker_size": 6,
            "dpi": 300,
            "grid": False,
            "spine_top": False,
            "spine_right": False,
        },
        "acm": {
            "font_family": "serif",
            "font_serif": ["Times New Roman", "Libertine"],
            "font_size": {"label": 9, "tick": 8, "legend": 8, "title": 10},
            "fig_width": {"single": 3.3, "double": 6.75},
            "fig_height_ratio": 0.75,
            "line_width": 1.3,
            "marker_size": 5,
            "dpi": 300,
            "grid": False,
            "spine_top": False,
            "spine_right": False,
        },
        "generic": {
            "font_family": "serif",
            "font_serif": ["DejaVu Serif", "Times New Roman"],
            "font_size": {"label": 11, "tick": 10, "legend": 10, "title": 12},
            "fig_width": {"single": 4.0, "double": 7.5},
            "fig_height_ratio": 0.75,
            "line_width": 1.5,
            "marker_size": 6,
            "dpi": 300,
            "grid": False,
            "spine_top": False,
            "spine_right": False,
        },
    }

    config = presets.get(journal, presets["generic"])
    config["journal"] = journal

    path = os.path.join(output_dir, "style_config.json")
    with open(path, "w") as f:
        json.dump(config, f, indent=2)
    print(f"  Created: {path} (journal={journal})")
    return path


def create_readme(output_dir: str) -> None:
    """Create a placeholder README.md."""
    path = os.path.join(output_dir, "README.md")
    content = """# Paper Figures

Generated by `paper-figures` skill.

## Directory Structure

- `src/` — Python source code for each figure
- `export/` — Final outputs (PDF + SVG + PNG)

## Figures

| ID | Filename | Type | Caption |
|----|----------|------|---------|

*Run the skill to populate this table.*
"""
    with open(path, "w") as f:
        f.write(content)
    print(f"  Created: {path}")


def scan_project() -> dict:
    """Scan the current directory for data sources."""
    info = {
        "csv_files": [],
        "model_files": [],
        "log_files": [],
        "config_data": None,
    }

    for root, dirs, files in os.walk("."):
        # Skip hidden dirs and venv
        dirs[:] = [d for d in dirs if not d.startswith(".") and d != "__pycache__" and d != "venv" and d != ".venv"]

        for f in files:
            path = os.path.join(root, f)
            rel = os.path.relpath(path, ".")

            if f.endswith(".csv"):
                info["csv_files"].append(rel)
            elif f.endswith(".py"):
                try:
                    with open(rel) as fh:
                        content = fh.read()
                    if "nn.Module" in content or "class " in content:
                        info["model_files"].append(rel)
                except Exception:
                    pass
            elif f.endswith(".log") or "metrics" in f.lower():
                info["log_files"].append(rel)

    return info


def main():
    parser = argparse.ArgumentParser(description="Setup figure directory structure")
    parser.add_argument("--output-dir", default="figures", help="Output directory name")
    parser.add_argument("--journal", default="generic",
                        choices=["ieee", "nature", "elsevier", "acm", "generic"],
                        help="Target journal style")
    parser.add_argument("--scan-only", action="store_true", help="Only scan for data sources")
    args = parser.parse_args()

    if args.scan_only:
        info = scan_project()
        print(json.dumps(info, indent=2))
        return

    print("Setting up figure directories...")
    setup_figure_dirs(args.output_dir)

    print("\nCreating default style config...")
    create_default_style(args.output_dir, args.journal)

    print("\nCreating README...")
    create_readme(args.output_dir)

    print("\nScanning project for data sources...")
    info = scan_project()
    if info["csv_files"]:
        print(f"  CSV files found: {info['csv_files']}")
    if info["model_files"]:
        print(f"  Model files found: {info['model_files']}")
    if info["log_files"]:
        print(f"  Log files found: {info['log_files']}")

    print(f"\nDone! Figure directory ready at: {args.output_dir}/")
    print(f"  src/     — place generated Python code here")
    print(f"  export/  — final PDF/SVG/PNG outputs go here")


if __name__ == "__main__":
    main()
